version: "3.7"

services:
  web:
    image: nginx:alpine
    volumes:
      - ./docker/nginx/nginx.template:/etc/nginx/conf.d/nginx.template
      - "./:/var/www/html"
    ports:
      - "8888:80"
    restart: always
    environment:
      - NGINX_HOST=senhas.test
      - NGINX_PORT=80
    command: sh -c "envsubst \"`env | awk -F = '{printf \" $$%s\", $$1}'`\" < /etc/nginx/conf.d/nginx.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    depends_on:
      - php
  node:
    build:
      context: ./docker/node
    volumes:
      - "./:/app"
    restart: always
    ports:
      - "6001:6001"
  mysql:
    build:
      context: ./docker/mysql
    volumes:
      - "db_data:/var/lib/mysql"
    container_name: mysql-container
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "app.123"
      MYSQL_DATABASE: tap
  php:
    build:
      context: ./docker/php
    volumes:
      - "./:/var/www/html"
    ports:
      - "9000:9000"
    depends_on:
      - mysql
    environment:
      - DB_HOST=mysql
      - DB_DATABASE=tap
      - DB_USERNAME=root
      - DB_PASSWORD=app.123
      - APP_URL=https://164a444a.ngrok.io
      - FIREBASE_SERVER_KEY=AAAABaz34R0:APA91bF0yMaFSIhiCYgkUFf2g1PDV2C4a2To1DJi2JHi1DlN6TzuVGd6xvwlvJTVpU3byGBESOhU8zSixg9Pvg4fo68u8BaNkRQgdU7G9h8Wv1h3B9fAz8Ysm8NCaaNdvGhR0Bq6o23w
volumes:
  db_data:
